### ISSUE TITLE
function addMedipsEnrichmentFactors() terminates with error 

### ISSUE THREAD

**Issue by anjalisa** [cruk-mi/mesa#1]
Hello, 

Running the function `makeQset()` with the parameter set `CNVmethod = "qseaPooled" , coverageMethod = "qseaPaired"` works smoothly until function `addMedipsEnrichmentFactors()` is reached. 
Error occurs at the following lines within the function `addMedipsEnrichmentFactors()` : 

```
enrichDataMeCap <- parallel::mclapply(pulldownFileNames,
                                       function(x){
                                       calculateCpGEnrichment(x, BSgenome, exportPath = exportPath,
                                                           extend = extend, shift = shift, uniq = uniq,
                                                           chr.select = chr.select, paired = paired)
                                  }, mc.cores = nCores) %>%
  do.call(rbind, . )
 
qseaSet@sampleTable <- qsea::getSampleTable(qseaSet) %>%  
   dplyr::bind_cols(dplyr::select(enrichDataMeCap,-file))

```
The parallelisation with `mclapply()` somehow does not seem to run smoothly all the time. 
Additionally, it states that `dplyr::select` can't be applied to a matrix.

**Comment by SPPearce** [comment]
Hi Anja,

Thank you for the bug report and the pull request to try and fix it, very much appreciated!
I'll take a look at the PR tomorrow, but just from a quick look at this function I think it needs the arguments checking (it has `paired = TRUE` being set by default for instance, which will probably mean it fails on single-ended reads too.

**Comment by SPPearce** [comment]
I think this has been fixed now, in the new version I have just pushed.
