### ISSUE TITLE
`plotRegionsHeatmap` fails if `regionsToOverlap` has multiple regions that overlap the same 300bp window.

### ISSUE THREAD

**Issue by paddyharker1005** [cruk-mi/mesa#18]
If the regions given to `regionsToOverlap` has some regions that overlap the same 300bp window, `plotRegionsHeatmap` will give the following error:

`Error in '.rowNamesDF<-'(x, value = value) : 
  duplicate 'row.names' are not allowed`

To reproduce this error run `qseaSet %>% plotRegionsHeatmap(regionsToOverlap = mesa::hg38UltraStableProbes)` with any qseaSet. There are some hyperStable probes which overlap the same windows.

I believe this is an issue with the `plyranges::join_overlap_left()` function in `getWindowAnnotation()`, leading to multiple matches with the same 300bp window.

**Comment by SPPearce** [comment]
Fixed in #23
