### ISSUE TITLE
`makeQset` with CNV method `MeCap` does not properly pass fragment length to `qsea::addCNV`

### ISSUE THREAD

**Issue by lbeltrame** [cruk-mi/mesa#20]
As the subject says. 

The code does this, when using `MeCap` as option for the CNV method:

https://github.com/cruk-mi/mesa/blob/212a791cb4da2d2d2c099c4ef53b4b71d5f1ee65/R/makeQset.R#L249

However, it doesn't discriminate whether only read pairs or R1s + read pairs are used. If called with this signature, the corresponding method in qsea

https://github.com/MatthiasLienhard/qsea/blob/3cdd22d3738857066fa7ab786e456fa0b6c92951/R/qsea.addCNV.R#L3

will have `fragment_length` set to `NULL`. 

It then goes there...

https://github.com/MatthiasLienhard/qsea/blob/3cdd22d3738857066fa7ab786e456fa0b6c92951/R/qsea.addCNV.R#L65

And then to `addCoverage`. Now, if we are using R1s along with proper pairs, some reads will *not* be paired, and hence will trigger this condition:

https://github.com/MatthiasLienhard/qsea/blob/3cdd22d3738857066fa7ab786e456fa0b6c92951/R/qsea.getCoverage.R#L6

And since we do not specify `fragment_length` here, an exception will be raised.

There are two ways to handle this:

- If the `MeCap` method does *not* allow for unpaired reads, make the function fail early (incompatible options)
- If instead it is allowed, pass the fragment length to `addCNV`.

**Comment by lbeltrame** [comment]
I think this also occurs in other use-case scenarios.

**Comment by SPPearce** [comment]
Thanks for reporting this, I will try and look at it next week.

**Comment by SPPearce** [comment]
Fixed in #21
