### ISSUE TITLE
exceeding the memory limit when calculating DMRs

### ISSUE THREAD

**Issue by shufanzhang** [cruk-mi/mesa#3]
When I try to calculate DMRs between SCLC and NCC cfDNA, the task exceeding the memory limit (100G) and I have to stop it.
```
qseaSetcfDNA <- read_rds("qseaSets/cfDNA_All_min50_max1000_w300_q10.rds")
SCLCcfDNA_DMRs <- qseaSetcfDNA %>%
  filterQset(secondSample!= "TRUE") %>%
  calculateDMRs(variable = "tumour",
                contrastsToDo = tibble(sample1 = "Tumour",
                                       sample2 = "Normal"),
                minNRPM = 1,
                fdrThres = 0.001)
```
`Error in reducer$value.cache[[as.character(idx)]] <- values`

So, I change some parameters in **makeDMRs.R**：
**parallel=TRUE** in **qsea::fitNBglm** and **qsea::addContrast** were removed，for the default parameter is parallel=FALSE
```
  qseaGLM <- qsea::fitNBglm(qseaSet,
                                             design,
                                             keep = keepIndex,
                                             minRowSum = 0,
                                             norm_method = "beta",
                                             verbose = FALSE)
qseaGLM <- qsea::addContrast(qseaSet,
                                                  qseaGLM,
                                                  contrast = limContrast,
                                                  name = conNameClean,
                                                  verbose = FALSE)
```
I also remove **suppressMessages()**, Not necessary, just output the information for debugging purposes.
Then, we reload the package，everything is OK !
`devtools::load_all("your_directory/mesa",reset = TRUE)`
Modifications to **mesa** will make the calculation of DMRs slower, but relatively, we can calculate a sizable data set within the 100G memory limit.

**Comment by SPPearce** [comment]
Hi @shufanzhang . 
Sorry for the delay, but we finally have a new release on the main branch, bringing the internal development we have been doing back to github.
This includes an overhaul for the function naming, and an entirely different way of specifying the parallelisation.
By default, the package will not use parallel processing, you can turn it on globally by using the 
`setMesaParallel` function.
